### ISSUE TITLE
Rename pic 

### ISSUE THREAD

**Issue by Contemp** [yairEO/photobox#115]
Hello !!!
I like your plugin and I was trying to add both a button + an  input type="text"  in data-pb-captionLink... But it doesnt work : 
When I click on my button, which shows correctly, I get a 403 : You don't have permission to access /myWeb/myFolder/<button id= on this server.

Could you kindly help, please ?
Same thing with the input, as soon as I start typing something in, I get redirected to a 403.
Thanks

**Comment by yairEO** [comment]
Please create a proper test page so I could see what you're trying to do and perhaps help

**Comment by Contemp** [comment]
https://jsfiddle.net/Contemp/14y6ddg3/
Wishing that what I've done is easy to understand and complete > I'm not sure of the linkage of external resources,
Thanks for your interest and help

**Comment by yairEO** [comment]
why are you trying to place an input inside the link?

**Comment by Contemp** [comment]
The reason why is quite obvious : I don't have a clue of how I 'm supposed to proceed
in order to enable the owner of a gallery to rename/delete his pics when displayed full-size. I've been looking for hours on the whole internet & asking on forums in 3 languages so far, and found nothing about that. 

I have to pass a form somewhere and somehow, I've tried many other differents things and for now I'm still stuck. 
Would be lovely of your part  if you could 'suggest', or better said show the way to achieve this request, which seems so simple to u. Lucky u

**Comment by yairEO** [comment]
you want to put a rename `input` and a **"delete"** button when showing the the photobox (single image full-view mode)? I don't think you can do it out-of-the-box with the current code..I might need to add a custom jQuery event so you would know an image is about to appear and then add your custom HTML. 

Also, you do not need a form, but only an input with a name and value, and a `<button>`, and you simply use AJAX to when an action happens, to let the server knows and do something with it.

**Comment by Contemp** [comment]
Hi, 
Yes indeed >   when showing the photobox : single image full-view mode. as per attached picture.
ok, I take note for the uncessary form tags. and yes, I wanted to call $.ajax to post / get the new title, + description, or to delete a given pic. 
When do u plan to have that custom jquery event set-up ? :)
Thank u
![example](https://cloud.githubusercontent.com/assets/17417696/13898255/a25d401a-edcb-11e5-9159-683b24ee15fe.jpg)

**Comment by yairEO** [comment]
I see, thank you. that is a completely different problem.
The one I fixed was this: just before showing the next photo, you would briefly see the one that faded out and then it would change to the one you are supposed to see.

This issue is something else: it is showing the photo that should transition-in before it is being animated, and then it animates it. Since I don't see this issue on 2 windows machines, I would conclude this is a MAC issue. 

I don't know anyone who has a MAC computer and I don't have an account on Browserstack, so I can only try and guess what causes this issue...shooting blindly.

Can you please check Firefox also?

**Comment by jrondorf** [comment]
Your are mixing the issues :-)
See my answer in #114

**Comment by yairEO** [comment]
I've updated the code so you could manipulate the caption using a template string. 
it's called `captionTmpl` and its default value is :

    '<div class="title">{title}</div><div class="counter">({currentImageIdx}/{totalImagesCount})</div>'

You can add/modify/remove it and pass it as a `settings` to photobox.

Another way - there is the `beforeShow` setting which you can pass your callback function to. it has a single argument which is the `<a>` element which is associated with the image that is about to be shown. (hence "beforeShow"). You can use this callback to insert you custom HTML to photobox., for example, inside `.pbCaptionText`. (you only need a special identifier for each image in your case so you would know which one to delete/rename in the database)

**Comment by Contemp** [comment]
Thanks for that.
However, I really dont understand how to implement either one solution or the other. I'm lost since I still don't have your level in jQuery. I've tried several things which I guessed I understood, but finally I don't. :S  and ... 

Would it be possible for you to show a more concrete example, maybe by editing my fiddle ?
https://jsfiddle.net/Contemp/14y6ddg3/#&togetherjs=eGguyVq8rM
You could share that fiddle on your page too... It's just an idea... so anyone in my case could benefit of it. What do u think?

**Comment by Contemp** [comment]
Allo ? Do u hear me?

**Comment by yairEO** [comment]
Here you go: https://jsfiddle.net/14y6ddg3/8/

Now all you need is to style it and bind the appropriate events to the buttons and then send any data you wish to the server.

**Comment by Contemp** [comment]
Great !  Thank u!  We're almost done !! But not yet as  this system doesn't seem to work when one gets her pics  loaded through php:

Even when placing Photobox script in the middle of my mysql_while_loop,  my **var jquery_var= "<?php echo php_var ?>",** do not update when navigating from pic to pic.

```
$query = mysql_query("SELECT filename from pictures");
while ($data= mysql_fetch_assoc($query))
       **{ **$filename = $data['filename'];
  ?>
<script type="text/javascript">
 $(document).ready(function() { 
 
 var gallery_file = "<?php echo $galleryname."/".$file; ?>";
 var inp_val = "<?php echo $filename; ?>";
 var delete_id = "<?php echo 'delete'.$galleryname.'/'.$file; ?>";
                                             
$('#gallery').photobox('a',{  
  time:0,
 history: false,
 thumbs: false,
 captionTmpl: '<div class=""><input type="text" id="'+inp_val+'" class="" value="'+gallery_file+'" ><button id="'+delete_id+'" class="delete_btn"> <div>', 
```

The ideal would be to have a <a href="#" captionTmpl='<div class=""><input type="text" id="'+inp_val+'" class="" value="'+gallery_file+'" ><button id="'+delete_id+'" class="delete_btn"> <div>', 


Or maybe I missed something...

Looking fwd to hearing from u again :)

**Comment by yairEO** [comment]
why do you need an `id` for the captionTmpl elements? you can just put it on the `<a>` elements which hold the images of the gallery then you can use jQuery `closest('a')`  to get the anchor link and extract the `id` from it. That is the best way, and even better is to use parse the id from the image href itself if possible.

**Comment by Contemp** [comment]
Ok, I got to your point, but I still experience a problem.
`<a id="filename" href="#">img</a>`

```
}, 
function() {
var test = $(this).attr('id'); //console.log(test);//OK
var ctn = $(this).find('input_ctn'); //console.log(ctn); // OK
var inputo = ctn.find('.titre_pic');console.log(inputo); //OK

// FROM here it stops responding ... 
$(inputo).on('mouseleave, click, blur',function(){ alert('i'); console.log('click');  // No answer
var inpval = $(inputo).val();console.log(inpval);  // No answer either
}); 
``` 
I already asked on 15 international forums about how to get my vals, in same conditions, and nobody answered.
Can u kindly tell the girl what the solution is ?
Thank u	again :)

**Comment by yairEO** [comment]
no problem. 

This is not a valid jQuery code: `$(inputo).on('mouseleave, click, blur',function(){...`
There are no commas when you define events with the `on` method. only space-separated list.

Here's what you should do in a very basic way:

    //////////////////////////////////
    // Initialize Photobox

    var currentImageId;

    $('#gallery').photobox('a', {
        thumbs: false,
        beforeShow : onBeforePhotoboxShow,
        captionTmpl :  '<input value="{title}">\
                        <button class="delete">&times;</button>\
                        <textarea></textarea>\
                        <button class="save">update</button>\
                        <div class="counter">({currentImageIdx}/{totalImagesCount})</div>'
    });


    //////////////////////////////////
    // Events

    $('#pbCaption').on('blur', 'input', onInputBlur)
                   .on('blur', 'textarea', onTextareaBlur)
                   .on('click', 'button.delete', onDeleteBtnClick)



    //////////////////////////////////
    // Callbacks


    function onBeforePhotoboxShow(anchor){
        // set current image id by taking it from the anchor itself
        currentImageId = anchor.id;
    }

    function updateServer(URL, value){
        return $.ajax({
            method      : 'POST',
            data        : { id:currentImageId, value:value},
            url         : URL,
            dataType    : 'json',
            contentType : 'application/json'
        })
    }


    function onInputBlur(){
        updateServer(URL, this.value);
    }

    function onTextareaBlur(){
        updateServer(URL, this.value);
    }

    function onDeleteBtnClick(){
        // here all is needed is the URL to let the server know it 
        // should delete the photo (maybe even pass another "method")
        updateServer(URL);
    }

**Comment by Contemp** [comment]
Merci, c'est très gentil.
I really need to print  those basics in my head !!!
Okay, I guess now I won't have to disturb u again,(hope so). 
Merci encore for your update & care

**Comment by yairEO** [comment]
Thank you :) good luck with what you're trying to do!

**Comment by Contemp** [comment]
:)  Merci. I'll send u a link once my baby is borned

**Comment by Contemp** [comment]
Can I ask a personal question, just for.. ? Where are u from?
I'm French, living in ..France... for now. and u ? just like that

**Comment by Contemp** [comment]
Heya, I'm back, unfortunately, 

My 1rst new problem, lies in : onBeforePhotoboxShow
Only the 1st [pic clicked]   displays its title & description, the other don't. They do display placeholder texts instead...
Also, when navigating to and fro the 1st clicked pic, its title & description fades in but instantaneously desappears and my placeholders are shown instead.

```
var pass="";
function onBeforePhotoboxShow(anchor)    
{   currentImageId = anchor.id; 
    pass ="pass";
  $.ajax({ type   : 'POST',
	         url    : 'ajx/5_photobox_display_descriptions.php',					
	         data   : { currentImageId:currentImageId, pass:pass},					
		success: function(setFields)
                              { var data = JSON.parse(setFields);
                                $('#pbCaption').each(function() {var inp= $(this).find('input');  inp.val(data.title); }); // only displays data in the 1st clicked pic
			       var Tarea = $('#pbCaption').find('textarea'); Tarea.val(data.description); // only displays data in the 1st clicked pic equally
			     }
                })
}
```



My 2nd problem, is with delete : I'd like to ask thru a confirm/dialog box whether we must proceed with the deletion or not, but I get as many popup window as my *gallery counts with pictures*, and I'm unable to solve this case.
* Sorry for my my english.. Not sure it's well said...
```
var updater="";			   
 
$('#pbCaption').on('blur','input',function() {      // OK DB is updated   
     var value=$(this).val();  
      $.ajax({
				type        : 'POST',
				data        : { currentImageId:currentImageId, value:value, updater:'title'},
				url         : 'ajx/5_photobox_display_descriptions.php',     
            })
});

$('#pbCaption').on('blur','textarea',function() {           // OK
	   
     var value=$(this).val();  
      $.ajax({
				type        : 'POST',
				data        : { currentImageId:currentImageId, value:value, updater:'description'},
			 	url         : 'ajx/5_photobox_display_descriptions.php',     
            })
});


$('#pbCaption').on('click', '.delete_btn', function() 
{  var delid=$(this);
   if (delid)           //  I want to popup a confirm only once per button clicked....
     {
          if (confirm('Tu es sur le point de supprimer cette image. Continuer ?')) 
			 {
				  $.ajax({
							type        : 'POST',
							data        : { currentImageId:currentImageId, updater:'deleter'},
							url         : 'ajx/5_photobox_display_descriptions.php',     
						})
			 }
	   }
	   
});

```

On server -side, everything is processed correctly, but on the j-dark-side, it looks like i'm a useless jester

**Comment by Contemp** [comment]
So ?
No answer ??? 15days now that I've been on it, and nobody in the World answered my questions about handling data within a gallery in that case.

If  `myInput.val(myPHPvarSentByAjax)` do not show the data when navigating from pic to pic, how am I supposed to proceed ?
Why don't u answer ?

**Comment by yairEO** [comment]
I don't answer because just like your question, I get others as well, and I am working full-time as team manager so I have to answer my team's questions as well, so basically my day is all around fixing things and answering question, and sometimes it's just tiring me to the point I don't feel like answering anymore, and let people figure things themselves, just like I did when I started, when the internet was new and empty of information, and people read paper books :) 

btw, instead of:

    var value=$(this).val();  
    ...

You can do this:

    $.ajax({
                type        : 'POST',
                data        : { currentImageId:currentImageId, value:this.value, updater:'title'},
                url         : 'ajx/5_photobox_display_descriptions.php',     
          })

And I see you didn't write the code the way I suggest you to, which annoyed me, since I took the time to construct you a well-designed code.

You can see the `console.log` calls in [this demo](https://jsfiddle.net/14y6ddg3/9/). it is working well. try to think why is it working well in this example page and not in yours

**Comment by gray-magic** [comment]
Hi Contemp, 
check your Vape6 account on alsacreation.
